FROM apache/airflow:2.10.4-python3.11

USER root

RUN apt-get update && apt-get install -y \
    openjdk-17-jdk \
    && apt-get clean

USER airflow

COPY docker/requirements-airflow.txt /requirements-airflow.txt

RUN pip install --no-cache-dir -r /requirements-airflow.txt